### ISSUE TITLE
' in names

### ISSUE THREAD

**Issue by elmic11111** [Celeo/EveTrackers#42]
So we have some members who have ' in their names. The tracker removes them so it's hard to find them to pay them. Is there a way we can include them but maybe use the %code for the so to avoid injection issues?

**Comment by Celeo** [comment]
This is definitely something that should be handled server-side; I'll take
a look.

**Comment by elmic11111** [comment]
Maybe there somewhere in the database we could add a notes field that I could use?

**Comment by Celeo** [comment]
I found a bug in the script that updates names (related to this but not fixing the issue): 59f7fbaef0d0e222d6e31e565c01862c5664745e

**Comment by Celeo** [comment]
Added to ADMINS list to access model admin pages.
